image: atlassian/default-image:3

clone:
  depth: full

pipelines:
  branches:
    main:
      - step:
          name: Pushing to github repo
          script:
            - echo "Uploading to github repo"
            - git push --mirror git@github.com:dapize/hlds-pack.git
      - step:
          name: Pushing to Dockerhub
          script:
            - docker build -t dapize/hlds-pack:latest --no-cache .
            - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
            - docker push dapize/hlds-pack:latest
          services:
            - docker
